#### Build stage
FROM openjdk:17
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package  

#### Package stage
FROM openjdk:17
COPY --from=build /home/app/target/product-server-0.0.1-SNAPSHOT.jar /usr/local/lib/emart-productapi.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/local/lib/emart-productapi.jar"]
